### ISSUE TITLE
Every second time role is run, it fails when trying to create bootstrap user.

### ISSUE THREAD

**Issue by Slugger70** [galaxyproject/ansible-galaxy-tools#20]
When using this role, it works fine the first time. However, if I run the role again it fails when creating the bootstrap user (it says that it already exists.) If I re-run the role again, it works fine. Then on the 4th time it fails again etc..

Error message: 

failed: [ip-address] => {"changed": true, "cmd": ["/mnt/galaxy/galaxy-app/.venv/bin/python", "manage_bootstrap_user.py", "-c", "/mnt/galaxy/galaxy-app/config/galaxy.ini", "create", "-e", "cloud@galaxyproject.org", "-p", "TODO-GenerateRandomOrDeleteBootstrapUser"], "delta": "0:00:03.708041", "end": "2016-02-08 00:13:20.316735", "rc": 1, "start": "2016-02-08 00:13:16.608694", "warnings": []}
stderr: Traceback (most recent call last):
  File "manage_bootstrap_user.py", line 207, in <module>
    create_bootstrap_user(args.config, args.username, args.email, args.password)
  File "manage_bootstrap_user.py", line 159, in create_bootstrap_user
    user = get_or_create_user( app, user_email, password, username )
  File "manage_bootstrap_user.py", line 99, in get_or_create_user
    return create_user( app, email, password, username )
  File "manage_bootstrap_user.py", line 85, in create_user
    app.model.security_agent.create_private_user_role( user )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/security/**init**.py", line 768, in create_private_user_role
    self.sa_session.flush()
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/scoping.py", line 150, in do
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/session.py", line 2004, in flush
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/session.py", line 2122, in _flush
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/session.py", line 2086, in _flush
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/unitofwork.py", line 373, in execute
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/unitofwork.py", line 532, in execute
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/persistence.py", line 174, in save_obj
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/persistence.py", line 762, in _emit_insert_statements
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 914, in execute
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
  File "/mnt/galaxy/galaxy-app/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/default.py", line 442, in do_execute
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "ix_role_name"
DETAIL:  Key (name)=(cloud@galaxyproject.org) already exists.
 [SQL: 'INSERT INTO role (create_time, update_time, name, description, type, deleted) VALUES (%(create_time)s, %(update_time)s, %(name)s, %(description)s, %(type)s, %(deleted)s) RETURNING role.id'] [parameters: {'update_time': datetime.datetime(2016, 2, 8, 0, 13, 20, 173581), 'name': u'cloud@galaxyproject.org', 'deleted': False, 'create_time': datetime.datetime(2016, 2, 8, 0, 13, 20, 173551), 'type': 'private', 'description': u'Private Role for cloud@galaxyproject.org'}]

FATAL: all hosts have already failed -- aborting

**Comment by afgane** [comment]
So I'm not able to replicate this Simon. Are you running the latest code in the repo? Some time ago, there were a few changes to creation of the bootstrap user. 

I pushed a couple of changes to fix logging and explicitly set the username so perhaps try just running the script manually and see if that makes any difference. Let me know how that goes and I'll look at it again then.

**Comment by Slugger70** [comment]
It was the version of the code from the ansible-galaxy.. Once I grabbed the github version there was no longer a problem.
